# Salar Rahmanian - .zshrc file
#
# Custom Completion Funcs
fpath+=~/.zfunc

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# General
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export TERM=xterm-256color
alias vim="nvim"
alias notes="cd ~/notes; nvim"
export EDITOR=nvim

# Use CTAGS version installed via brew instead of xcode (used by vim plugin)
export CTAGS=/usr/local/bin
export PATH=$CTAGS:$PATH

# Yarn
export PATH=$PATH:/usr/local/Cellar/node/7.2.0/bin

# Go Lang
export GOPATH=$HOME/goprojects
export PATH=$PATH:$GOPATH/bin

# Python
export CFLAGS="-I$(xcrun --show-sdk-path)/usr/include"
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

# Java
export JAVA_HOME=$(/usr/libexec/java_home)

# Scala
export SCALA_HOME=/usr/local/opt/scala/idea
export PATH=$PATH:$SCALA_HOME/bin
export BROWSER="firefox %s"

# C#
export PATH=$PATH:/usr/local/share/dotnet

# aliases 
alias dc="docker-compose"
alias dm="docker-machine"
alias kb="kubectl"
alias kp="kops"
alias mk="minikube"

# Shell improvements
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
source <(kubectl completion zsh)

# k8
minikube status | grep -a "Stopped" &> /dev/null
if [ $? -ne 0 ]; then
    eval $(minikube docker-env)
else
    echo "minikube not running"
fi

